name: "Build MacOS x64"
on: workflow_dispatch
env:
    WAVETERM_VERSION: 0.5.3
jobs:
    runbuild:
        name: "Build MacOS x64"
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                go-version: '1.21.5'
                cache-dependency-path: |
                    wavesrv/go.sum
                    waveshell/go.sum
            - run: brew tap scripthaus-dev/scripthaus
            - run: brew install scripthaus
            - uses: actions/setup-node@v4
              with:
                node-version: '21.5.0'
                cache: 'yarn'
            - run: yarn --frozen-lockfile
            - run: scripthaus run build-package
            - uses: actions/upload-artifact@v3
              with:
                name: waveterm-build-darwin-x64
                path: out/make/zip/darwin/x64/*.zip
                retention-days: 2


