name: "Build MacOS x86"
on: workflow_dispatch
env:
    WAVETERM_VERSION: 0.5.3
jobs:
    runbuild:
        name: "Build MacOS x86"
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                go-version: '1.21.5'
            - run: brew tap scripthaus-dev/scripthaus
            - run: brew install scripthaus
            - run: yarn --frozen-lockfile
            - run: scripthaus run build-package
            - uses: actions/upload-artifact@v3
              with:
                name: waveterm-build-darwin-x86
                path: out/make/zip/darwin/x86/*.zip
                retention_days: 2


