name: Publish a new release
on:
    release:
        types: [published]
env:
    NODE_VERSION: "21.5.0"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{env.NODE_VERSION}}
                  cache: "yarn"
            - name: Get the version
              id: get_version
              run: |
                  VERSION=$(node -e 'console.log(require("./version.js"))')
                  echo "WAVETERM_VERSION=${VERSION}" >> "$GITHUB_OUTPUT"
            - name: Download staged artifacts
              run: |
                  . ./buildres/download-staged-artifacts.sh
              env:
                  AWS_ACCESS_KEY_ID: "${{ secrets.S3_USERID }}"
                  AWS_SECRET_ACCESS_KEY: "${{ secrets.S3_SECRETKEY }}"
                  AWS_DEFAULT_REGION: us-west-2
            - name: Generate Flatpak manifest
              run: node buildres/flatpak/generate-flatpak-manifest.js
